version: "3.5"
services:
  apimanager:
    container_name: apim
    hostname: apim
    image: wso2/wso2am:latest
    labels:
      name: wso2
    ports:
    - 8290:8290
    - 8253:8253
    - 9453:9453
  micros-java:
    image: meumicroservico
    container_name: springboot
    build: .
    ports:
        - 8080:8080
  banco:
   image: postgres:10
   environment:
    POSTGRES_PASSWORD: SENHAFORTE369
    POSTGRES_DB: msdb
    POSTGRES_USER: userms
   ports:
     - 5432:5432